name: Pull Request flow

on:
 pull_request: 
    types: [opened, synchronize, closed]

env:
  SEARCH_ITEM: sushi

jobs:
  Update-file:
    name: Updating version to ${{ github.event.inputs.newVersion }}
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code from the repository
        id: checkoutCode
        uses: actions/checkout@v2

      - name: Get pull request number
        id: getPullRequestNumber
        run: |
          PULL_NUMBER=$(jq --raw-output .pull_request.number "$GITHUB_EVENT_PATH")
          echo "::set-output name=pullNumber::${PULL_NUMBER}"

      - name: commenter
        uses: peter-evans/create-or-update-comment@v1
        with:
          repository: aa-ericaoytas/gha-playground-app
          issue-number: ${{ steps.getPullRequestNumber.outputs.pullNumber }}
          token: ${{ secrets.WORKFLOW_PAT }}
          body: |
            This is a test.
            - Status: Hungry
            - URL: https://www.google.com/maps/search/google+${{ env.SEARCH_ITEM }}
            Go get some.

            ** Hi ** 
            - Copy this code asdlkfjoljoitjaoijjaoisj: `sadfjhoijaoiesjoif This is code. Search item is ${{ env.SEARCH_ITEM }} adsfdsafefesafsadf`
            - Yes