name: Test conditionals

on:
  push:
    branches:
      - main
  pull_request: 
    types: [opened, synchronize, closed]

env:
  APPLICATION_NAME: test-app
  TARGET_ENVIRONMENT: nonprod

jobs:
  close:
    if: github.event.pull_request.merged != 'true' && github.event.pull_request.state == 'closed'
    name: Run when PR closed
    runs-on: ubuntu-latest
    steps: 
      - name: Echo info
        run: |
          echo "INFO: github.event.pull_request.state"
          echo "${{ github.event.pull_request.state }}"
          echo "INFO: github.event.action"
          echo "${{ github.event.action }}"
          echo "INFO: github.event.pull_request.merged"
          echo "${{ github.event.pull_request.merged }}"
          echo "INFO: github.event_name"
          echo "${{ github.event_name }}"
          echo "INFO: github.ref"
          echo "${{ github.ref }}"  

  merge:
    if: github.event.pull_request.merged == 'true' && github.event_name == 'push'
    name: Run when PR merged 
    runs-on: ubuntu-latest
    steps:
      - name: Echo info
        run: |
          echo "INFO: github.event.push"
          echo "${{ toJson(github.event.push) }}"
          echo "INFO: github.event.action"
          echo "${{ github.event.action }}"
          echo "INFO: github.event_name"
          echo "${{ github.event_name }}" 
          echo "INFO: github.ref"
          echo "${{ github.ref }}" 

  pr-open-sync:
    if: github.event.pull_request.merged != 'true' && github.event.pull_request.state == 'open'
    name: Run when PR is opened & synchronized
    runs-on: ubuntu-latest
    steps:
      - name: Echo info
        run: |
          echo "INFO: github.event.pull_request.state"
          echo "${{ github.event.pull_request.state }}"
          echo "INFO: github.event.action"
          echo "${{ github.event.action }}"
          echo "INFO: github.event.pull_request.merged"
          echo "${{ github.event.pull_request.merged }}"
          echo "INFO: github.event_name"
          echo "${{ github.event_name }}"
          echo "INFO: github.ref"
          echo "${{ github.ref }}" 

  always-run:
    name: Run always
    runs-on: ubuntu-latest
    steps: 
      - name: Echo info
        run: |
          echo "INFO: github.event.pull_request.state"
          echo "${{ github.event.pull_request.state }}"
          echo "INFO: github.event.pull_request.merged"
          echo "${{ github.event.pull_request.merged }}"
          echo "INFO: github.event.push"
          echo "${{ toJson(github.event.push) }}"
          echo "INFO: github.event.action"
          echo "${{ github.event.action }}"
          echo "INFO: github.event_name"
          echo "${{ github.event_name }}"
          echo "INFO: github.ref"
          echo "${{ github.ref }}" 