name: Trigger other workflow in another repo

on:
  workflow_dispatch:
    inputs:
      newVersion:
        description: "New version to update to"
        required: true

env:
  APPLICATION_NAME: test-app
  TARGET_ENVIRONMENT: nonprod

jobs:
  Update-file:
    name: Updating version to ${{ github.event.inputs.newVersion }}
    runs-on: ubuntu-latest
    steps: 
      - name: Checkout Code from the repository
        id: checkoutCode
        uses: actions/checkout@v2

      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.WORKFLOW_PAT }}
          repository: aa-ericaoytas/GitHubActionsPlayground
          event-type: Update to ${{ github.event.inputs.newVersion }}
          client-payload: '{"actor": "${{ github.actor }}", "applicationName": ${{ env.APPLICATION_NAME }}", "applicationVersion": "${{ github.event.inputs.newVersion }}", "targetEnvironment": ${{ env.TARGET_ENVIRONMENT }}}'
